# Generated by Django 3.1 on 2020-07-30 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mongodb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
